<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOqxf0an\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOqxf0an/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOqxf0an.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOqxf0an\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOqxf0an\appProdProjectContainer([
    'container.build_hash' => 'Oqxf0an',
    'container.build_id' => 'dab05d5f',
    'container.build_time' => 1591215367,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOqxf0an');
