<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI4rp3at\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI4rp3at/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerI4rp3at.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerI4rp3at\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerI4rp3at\appDevDebugProjectContainer([
    'container.build_hash' => 'I4rp3at',
    'container.build_id' => 'bae6e7dd',
    'container.build_time' => 1593291564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI4rp3at');
